 # Using the pre-made node-red docker image
 FROM nodered/node-red-docker

 # Install ttn and mongodb nodes
 RUN npm install node-red-contrib-ttn
 RUN npm install node-red-contrib-mongodb3
 RUN npm install node-red-node-mysql